### ISSUE TITLE
[new feature]verify the hash of downloaded content

### ISSUE THREAD

**Issue by lookis** [henkaku/henkaku.github.io#16]
Thx you for the amazing website.
I encounter a network issue, some times my network is not stable, and the .bin/.xml file not download fully. but still try to install it, and the system will be a mess, that I have to clean the cookie, reset factory setting.. again and again.

could you verify the download content, or even resume transmission at break points?
thank you very much

**Comment by yifanlu** [comment]
It's not possible to implement such a system with github-pages. Sorry.
