### ISSUE TITLE
Henkaku.xyz/go page doesn't load when inserting a card coming from 3.63 system

### ISSUE THREAD

**Issue by mickael28** [henkaku/henkaku.github.io#20]
Hi,

I have a PS Vita 3.60 with a 16GB card and Henkaku has worked 100% all times, now I got a PSTV 3.63 and I was trying to instal ARK for PSP emulation there. 

I inserted the card in PSTV 3.63, now when I put it back in Vita 3.60 I get the message that I need to 'system update' to use the card or 'format' it. I select 'no' to both and then I launch my browser and try to go to 'henkaku.xyz/go'. 

The issue I'm having is that the site doesn't seem to load, the blue bar starts kind of loading, but when it reaches the .xy part, it just stops there.

Could you please have a look into this issue? Or can you think of any fix/workaround that I could try from my end?

Thanks!

**Comment by mickael28** [comment]
What is the duplicate of this one to keep a track on the original?,, I couldn't find any outstanding issues...

**Comment by xyzz** [comment]
Here: #21

**Comment by mickael28** [comment]
But #21 is talking about having 'no' card inserted. This one is talking about having a card inserted that worked with Henkaku, then putting that card in a 3.63 system, loading it back in the Vita 3.60 and having the issue of Henkaku web page freezing... ie, even with the card inserted?
